const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const minimap=document.querySelector('#minimap'),mctx=minimap.getContext('2d');
ctx.imageSmoothingEnabled=false;mctx.imageSmoothingEnabled=false;
const ui={playerName:document.querySelector('#player-name'),classLabel:document.querySelector('#class-label'),hpFill:document.querySelector('#hp-fill'),hpText:document.querySelector('#hp-text'),spFill:document.querySelector('#sp-fill'),spText:document.querySelector('#sp-text'),xpFill:document.querySelector('#xp-fill'),xpText:document.querySelector('#xp-text'),targetPanel:document.querySelector('#target-panel'),targetName:document.querySelector('#target-name'),targetHpFill:document.querySelector('#target-hp-fill'),targetHpText:document.querySelector('#target-hp-text'),questProgress:document.querySelector('#quest-progress'),battleLog:document.querySelector('#battle-log'),toast:document.querySelector('#toast'),helpToggle:document.querySelector('#help-toggle'),helpContent:document.querySelector('#help-content')};
const WORLD={width:2600,height:1700,margin:42},TAU=Math.PI*2;
const keys=new Set(),particles=[],texts=[],fx=[],spriteCache=new Map();
let now=performance.now(),lastFrame=now,selectedId=null,kills=0,objectiveComplete=false,toastTimer=null;
const camera={x:0,y:0},mouse={worldX:0,worldY:0};
const dirRow={down:0,left:1,right:2,up:3};
const classAt=l=>l>=16?'Sumo Sacerdote':l>=8?'Sacerdote':'Noviço';
const stored=JSON.parse(localStorage.getItem('roweb-save')||'{}');
const player={name:stored.name||'Aster',x:Number(stored.x)||1260,y:Number(stored.y)||900,radius:15,speed:225,dir:'down',moving:false,level:Number(stored.level)||1,xp:Number(stored.xp)||0,maxHp:110,hp:Number(stored.hp)||110,maxSp:80,sp:Number(stored.sp)||80,job:'Noviço',moveTarget:null,barrier:0,barrierMax:0,barrierUntil:0,barrierBurstDone:true,invulnerableUntil:0,flashUntil:0,attackingUntil:0,castingUntil:0};
player.job=classAt(player.level);
const classScale=()=>player.job==='Sumo Sacerdote'?1.45:player.job==='Sacerdote'?1.22:1;
const skills={normal:{name:'Ataque Normal',cost:0,cooldown:520,range:82,last:-99999},heal:{name:'Cura',cost:10,cooldown:1150,range:355,last:-99999},magnificat:{name:'Magnificat',cost:22,cooldown:5200,range:0,last:-99999},blessing:{name:'Benção',cost:16,cooldown:2600,range:385,last:-99999},kyrie:{name:'Kyrie Eleison',cost:25,cooldown:7000,range:0,last:-99999}};
const MOB_TEMPLATES={imp:{name:'Diabrete Rubro',maxHp:68,speed:78,damage:8,xp:24,radius:16,aggro:245},eye:{name:'Olho Profano',maxHp:92,speed:62,damage:11,xp:34,radius:19,aggro:280},bat:{name:'Morcego Abissal',maxHp:54,speed:112,damage:7,xp:20,radius:14,aggro:220},poring:{name:'Poring Demoníaco',maxHp:420,speed:54,damage:18,xp:180,radius:31,aggro:330,boss:true}};
const spawnPoints=[['imp',500,430],['bat',720,540],['eye',930,390],['imp',1660,400],['bat',1880,560],['eye',2110,420],['imp',420,1060],['bat',690,1280],['eye',980,1160],['imp',1690,1180],['bat',1990,1040],['eye',2200,1320],['poring',2240,820]];
function makeMob(id,type,x,y){const t=MOB_TEMPLATES[type];return{id,type,...t,x,y,spawnX:x,spawnY:y,hp:t.maxHp,alive:true,dir:'down',moving:false,angle:Math.random()*TAU,wanderUntil:0,attackAt:0,flashUntil:0,respawnAt:0,weakenUntil:0,vulnerableUntil:0,attackingUntil:0}}
const mobs=spawnPoints.map((e,i)=>makeMob(i+1,...e));
const scenery=[{type:'chapel',x:1300,y:250,w:430,h:270},{type:'altar',x:1300,y:720,w:170,h:86},{type:'grave',x:420,y:690},{type:'grave',x:520,y:750},{type:'grave',x:365,y:820},{type:'grave',x:2070,y:620},{type:'grave',x:2170,y:690},{type:'grave',x:2050,y:770},{type:'tree',x:305,y:315},{type:'tree',x:610,y:265},{type:'tree',x:1980,y:255},{type:'tree',x:2310,y:350},{type:'tree',x:285,y:1360},{type:'tree',x:2260,y:1380},{type:'crystal',x:1210,y:1360},{type:'crystal',x:1400,y:1400},{type:'pillar',x:1070,y:570},{type:'pillar',x:1530,y:570},{type:'ruin',x:780,y:900},{type:'ruin',x:1810,y:890}];
function colliderFor(s){if(s.type==='chapel')return{kind:'rect',x:s.x-s.w/2+18,y:s.y-s.h/2+55,w:s.w-36,h:s.h-80};if(s.type==='altar')return{kind:'rect',x:s.x-s.w/2+12,y:s.y-s.h/2+22,w:s.w-24,h:s.h-28};if(s.type==='grave')return{kind:'rect',x:s.x-16,y:s.y-10,w:32,h:26};if(s.type==='tree')return{kind:'circle',x:s.x,y:s.y+20,r:34};if(s.type==='crystal')return{kind:'circle',x:s.x,y:s.y+6,r:21};if(s.type==='pillar')return{kind:'circle',x:s.x,y:s.y+8,r:23};if(s.type==='ruin')return{kind:'rect',x:s.x-35,y:s.y-18,w:70,h:36};return null}
const solidColliders=scenery.map(colliderFor).filter(Boolean);
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false}
addEventListener('resize',resize);resize();
function log(msg,type='info'){const line=document.createElement('div');line.className=`log-${type}`;line.textContent=msg;ui.battleLog.append(line);while(ui.battleLog.children.length>5)ui.battleLog.firstChild.remove()}
function toast(msg){clearTimeout(toastTimer);ui.toast.textContent=msg;ui.toast.classList.remove('hidden');toastTimer=setTimeout(()=>ui.toast.classList.add('hidden'),2200)}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),lerp=(a,b,t)=>a+(b-a)*t,rand=(a,b)=>a+Math.random()*(b-a);
function directionFromVector(dx,dy){return Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up')}
function directionTo(t){return directionFromVector(t.x-player.x,t.y-player.y)}
function circleHitsRect(x,y,r,q){const cx=clamp(x,q.x,q.x+q.w),cy=clamp(y,q.y,q.y+q.h),dx=x-cx,dy=y-cy;return dx*dx+dy*dy<r*r}
function hitsScenery(x,y,r){for(const c of solidColliders){if(c.kind==='circle'){const dx=x-c.x,dy=y-c.y;if(dx*dx+dy*dy<(r+c.r)**2)return true}else if(circleHitsRect(x,y,r,c))return true}return false}
function hitsMob(x,y,r,ignore=null){for(const m of mobs){if(!m.alive||m===ignore)continue;const dx=x-m.x,dy=y-m.y;if(dx*dx+dy*dy<(r+m.radius-2)**2)return true}return false}
function blockedAt(entity,x,y,o={}){const r=entity.radius||14;if(x-r<WORLD.margin||x+r>WORLD.width-WORLD.margin||y-r<WORLD.margin||y+r>WORLD.height-WORLD.margin)return true;if(hitsScenery(x,y,r))return true;if(o.collideMobs!==false&&hitsMob(x,y,r,o.ignoreMob||null))return true;if(o.collidePlayer&&entity!==player){const dx=x-player.x,dy=y-player.y;if(dx*dx+dy*dy<(r+player.radius)**2)return true}return false}
function moveWithCollision(entity,dx,dy,o={}){let moved=false;if(dx&&!blockedAt(entity,entity.x+dx,entity.y,o)){entity.x+=dx;moved=true}if(dy&&!blockedAt(entity,entity.x,entity.y+dy,o)){entity.y+=dy;moved=true}return moved}
function resolveMobSeparation(){const a=mobs.filter(m=>m.alive);for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){const x=a[i],y=a[j];let dx=y.x-x.x,dy=y.y-x.y,d=Math.hypot(dx,dy)||.001,min=x.radius+y.radius-1;if(d>=min)continue;let push=(min-d)*.5;dx/=d;dy/=d;const ax=x.x-dx*push,ay=x.y-dy*push,bx=y.x+dx*push,by=y.y+dy*push;if(!hitsScenery(ax,ay,x.radius)){x.x=ax;x.y=ay}if(!hitsScenery(bx,by,y.radius)){y.x=bx;y.y=by}}}
function findFreeSpot(x,y,r,ignore=null){const p={radius:r};if(!blockedAt(p,x,y,{ignoreMob:ignore,collideMobs:true}))return{x,y};for(let ring=1;ring<=12;ring++){const rad=ring*26;for(let i=0;i<16;i++){const a=i/16*TAU,nx=x+Math.cos(a)*rad,ny=y+Math.sin(a)*rad;if(!blockedAt(p,nx,ny,{ignoreMob:ignore,collideMobs:true}))return{x:nx,y:ny}}}return{x:1300,y:900}}
for(const m of mobs){const p=findFreeSpot(m.x,m.y,m.radius,m);m.x=m.spawnX=p.x;m.y=m.spawnY=p.y}if(blockedAt(player,player.x,player.y,{collideMobs:true})){const p=findFreeSpot(1260,900,player.radius);player.x=p.x;player.y=p.y}
const selectedMob=()=>mobs.find(m=>m.id===selectedId&&m.alive)||null;
function nearestMob(max=Infinity){return mobs.filter(m=>m.alive).map(m=>[m,dist(player,m)]).filter(([,d])=>d<=max).sort((a,b)=>a[1]-b[1])[0]?.[0]||null}
function selectMob(m){selectedId=m?.id??null;if(m)log(`${m.name} selecionado.`)}
const xpNeeded=l=>75+l*l*18;
function recalcStats(heal=false){const oh=player.maxHp,os=player.maxSp,rank=player.job==='Sumo Sacerdote'?2:player.job==='Sacerdote'?1:0;player.maxHp=100+player.level*10+rank*45;player.maxSp=70+player.level*9+rank*32;if(heal){player.hp=player.maxHp;player.sp=player.maxSp}else{player.hp=clamp(player.hp+(player.maxHp-oh),1,player.maxHp);player.sp=clamp(player.sp+(player.maxSp-os),0,player.maxSp)}}
recalcStats(false);
function persist(){localStorage.setItem('roweb-save',JSON.stringify({name:player.name,x:Math.round(player.x),y:Math.round(player.y),level:player.level,xp:player.xp,hp:Math.round(player.hp),sp:Math.round(player.sp)}))}
setInterval(persist,5000);
function burst(x,y,color,count=16,speed=100,size=3,up=0){for(let i=0;i<count;i++){const a=Math.random()*TAU,v=rand(speed*.35,speed);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-up,born:now,life:rand(450,900),color,size:rand(size*.5,size*1.5),shape:Math.random()>.7?'diamond':'dot'})}}
function floatingText(x,y,text,color='#fff'){texts.push({x,y,text,color,born:now,life:900})}
function addFx(type,data={}){fx.push({type,born:now,life:data.life||800,...data})}
function gainXp(amount){player.xp+=amount;let need=xpNeeded(player.level);while(player.xp>=need){player.xp-=need;const old=player.job;player.level++;player.job=classAt(player.level);recalcStats(true);addFx('level',{x:player.x,y:player.y,life:1200});burst(player.x,player.y,'#ffe48b',46,155,3,35);toast(`Nível ${player.level}! ${player.job}`);if(old!==player.job)log(`Classe evoluída para ${player.job}.`,'good');need=xpNeeded(player.level)}persist()}
function damageMob(m,amount,color='#fff1a8',source='Dano sagrado'){if(!m?.alive)return;const vuln=m.vulnerableUntil>now?1.22:1,dmg=Math.max(1,Math.round(amount*vuln));m.hp-=dmg;m.flashUntil=now+160;floatingText(m.x,m.y-m.radius-26,`-${dmg}`,color);burst(m.x,m.y,color,8,70,2,8);if(m.hp<=0)killMob(m,source)}
function killMob(m,source){m.hp=0;m.alive=false;m.respawnAt=now+(m.boss?18000:7500);if(selectedId===m.id)selectedId=null;kills++;const xp=Math.round(m.xp*classScale());gainXp(xp);addFx('purify',{x:m.x,y:m.y,life:m.boss?1200:800,boss:m.boss});burst(m.x,m.y,m.boss?'#ff5aa2':'#c7b2ff',m.boss?55:24,m.boss?210:130,4,20);log(`${m.name} foi purificado por ${source}. +${xp} XP`,'good');if(m.boss)toast('Poring Demoníaco purificado!');if(kills>=12&&!objectiveComplete){objectiveComplete=true;gainXp(120);toast('Missão concluída: Purificação do Vale')}}
function spend(s){if(now-s.last<s.cooldown)return false;if(player.sp<s.cost){toast('SP insuficiente');return false}player.sp-=s.cost;s.last=now;return true}
function ensureTarget(range){let m=selectedMob();if(!m)m=nearestMob(range);if(m&&dist(player,m)<=range){selectedId=m.id;return m}toast('Nenhum demônio no alcance');return null}
function cast(name){const s=skills[name];if(!s)return;
 if(name==='normal'){const t=ensureTarget(s.range);if(!t||!spend(s))return;player.attackingUntil=now+240;player.dir=directionTo(t);addFx('slash',{x:t.x,y:t.y,life:300,dir:player.dir});damageMob(t,(13+player.level*1.7)*classScale(),'#f6e4c3','Ataque Normal');return}
 if(name==='heal'){const t=ensureTarget(s.range);if(!t||!spend(s))return;player.castingUntil=now+360;addFx('healCaster',{x:player.x,y:player.y,life:520});addFx('healTarget',{x:t.x,y:t.y,life:720});damageMob(t,(29+player.level*3.1)*classScale(),'#b4ffe2','Cura');const rec=Math.round((13+player.level*1.25)*classScale());player.hp=clamp(player.hp+rec,0,player.maxHp);floatingText(player.x,player.y-48,`+${rec} HP`,'#9dffd1');burst(player.x,player.y,'#aaffd3',12,65,2,28);return}
 if(name==='magnificat'){if(!spend(s))return;player.castingUntil=now+650;const radius=270+player.level*3;addFx('magnificat',{x:player.x,y:player.y,radius,life:1650});const pulses=[0,260,520];pulses.forEach((delay,i)=>setTimeout(()=>{const current=performance.now();for(const m of mobs)if(m.alive&&Math.hypot(player.x-m.x,player.y-m.y)<=radius+30){const prev=now;now=current;damageMob(m,(13+player.level*1.8)*classScale(),'#fff0a8',`Magnificat ${i+1}`);now=prev}player.sp=clamp(player.sp+4,0,player.maxSp)},delay));return}
 if(name==='blessing'){const t=ensureTarget(s.range);if(!t||!spend(s))return;player.castingUntil=now+420;addFx('blessing',{x:t.x,y:t.y,life:900});damageMob(t,(35+player.level*3.6)*classScale(),'#e7d2ff','Benção');t.weakenUntil=now+6500;t.vulnerableUntil=now+6500;return}
 if(name==='kyrie'){if(!spend(s))return;player.castingUntil=now+480;player.barrier=Math.round((42+player.level*6)*classScale());player.barrierMax=player.barrier;player.barrierUntil=now+6500;player.barrierBurstDone=false;addFx('kyrieCast',{x:player.x,y:player.y,life:900});kyrieBurst('Kyrie Eleison')}
}
function kyrieBurst(source){const radius=175+player.level*2;addFx('kyrieBurst',{x:player.x,y:player.y,radius,life:700});for(const m of mobs)if(m.alive&&dist(player,m)<=radius)damageMob(m,(23+player.level*2.2)*classScale(),'#bfeaff',source)}
function hurtPlayer(amount){if(now<player.invulnerableUntil)return;const blocked=player.barrier>0?Math.min(player.barrier,amount):0;if(blocked>0){player.barrier-=blocked;addFx('guard',{x:player.x,y:player.y,life:420});floatingText(player.x,player.y-52,'GUARD','#d5f4ff')}const left=amount-blocked;if(left>0)player.hp-=left;player.flashUntil=now+180;player.invulnerableUntil=now+520;if(player.barrier<=0&&!player.barrierBurstDone){player.barrierBurstDone=true;kyrieBurst('Kyrie — ruptura')}if(player.hp<=0){player.hp=player.maxHp;player.sp=player.maxSp;const p=findFreeSpot(1260,900,player.radius);player.x=p.x;player.y=p.y;player.moveTarget=null;toast('Você foi derrotado e retornou ao santuário.')}}
function updatePlayer(dt){let dx=0,dy=0;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(dx||dy)player.moveTarget=null;else if(player.moveTarget){const tx=player.moveTarget.x-player.x,ty=player.moveTarget.y-player.y,d=Math.hypot(tx,ty);if(d<8)player.moveTarget=null;else{dx=tx/d;dy=ty/d}}if(dx||dy){const l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;player.dir=directionFromVector(dx,dy);player.moving=moveWithCollision(player,dx*player.speed*dt,dy*player.speed*dt,{collideMobs:true})}else player.moving=false;player.sp=clamp(player.sp+dt*1.7,0,player.maxSp);if(player.barrier>0&&now>=player.barrierUntil){player.barrier=0;if(!player.barrierBurstDone){player.barrierBurstDone=true;kyrieBurst('Kyrie — ruptura')}}}
function updateMobs(dt){for(const m of mobs){if(!m.alive){if(now>=m.respawnAt){const p=findFreeSpot(m.spawnX,m.spawnY,m.radius,m);m.x=p.x;m.y=p.y;m.hp=m.maxHp;m.alive=true;m.flashUntil=now+300}continue}let dx=0,dy=0,dp=dist(m,player);if(dp<=m.aggro){const vx=player.x-m.x,vy=player.y-m.y,d=Math.hypot(vx,vy)||1;if(d>m.radius+player.radius+5){dx=vx/d;dy=vy/d}else if(now>=m.attackAt){m.attackAt=now+(m.boss?1250:900);m.attackingUntil=now+240;hurtPlayer(Math.round(m.damage*(m.weakenUntil>now?.75:1)))}}else{if(now>=m.wanderUntil){m.wanderUntil=now+rand(900,2400);m.angle+=rand(-1.7,1.7)}dx=Math.cos(m.angle);dy=Math.sin(m.angle)}if(dx||dy){m.dir=directionFromVector(dx,dy);const speed=m.speed*(dp<=m.aggro?1:.42);m.moving=moveWithCollision(m,dx*speed*dt,dy*speed*dt,{collideMobs:true,ignoreMob:m,collidePlayer:true});if(!m.moving&&dp>m.aggro)m.angle+=rand(1.2,2.4)}else m.moving=false}resolveMobSeparation()}
function updateEffects(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985;p.vy*=.985;if(now-p.born>=p.life)particles.splice(i,1)}for(let i=texts.length-1;i>=0;i--)if(now-texts[i].born>=texts[i].life)texts.splice(i,1);for(let i=fx.length-1;i>=0;i--)if(now-fx[i].born>=fx[i].life)fx.splice(i,1)}
function updateCamera(){camera.x=lerp(camera.x,clamp(player.x-innerWidth/2,0,Math.max(0,WORLD.width-innerWidth)),.11);camera.y=lerp(camera.y,clamp(player.y-innerHeight/2,0,Math.max(0,WORLD.height-innerHeight)),.11)}
function px(c,x,y,w,h,color){c.fillStyle=color;c.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function makePlayerSheet(job){const key=`p:${job}`;if(spriteCache.has(key))return spriteCache.get(key);const fw=36,fh=50,frames=4,rows=4,s=document.createElement('canvas');s.width=fw*frames;s.height=fh*rows;const c=s.getContext('2d');c.imageSmoothingEnabled=false;const pal=job==='Sumo Sacerdote'?{robe:'#f4f3ee',robe2:'#d7e3ef',trim:'#d39b58',accent:'#6b83ad',cape:'#b9c9dd',hair:'#d8bf9c'}:job==='Sacerdote'?{robe:'#efe7df',robe2:'#b34d55',trim:'#6d3842',accent:'#d7c6a1',cape:'#9b454f',hair:'#cba789'}:{robe:'#e9d4b5',robe2:'#b87955',trim:'#6c4638',accent:'#f4ead7',cape:'#b8896d',hair:'#bd7e5f'};for(let r=0;r<rows;r++)for(let f=0;f<frames;f++){const ox=f*fw,oy=r*fh,bob=f===1?1:f===3?-1:0,step=f===1?-2:f===3?2:0;px(c,ox+8,oy+43,20,3,'rgba(40,31,35,.18)');if(r===3){px(c,ox+10,oy+8+bob,16,11,pal.hair);px(c,ox+8,oy+18+bob,20,20,pal.cape);px(c,ox+11,oy+37+bob,6,7,'#56484b');px(c,ox+20,oy+37+bob,6,7,'#56484b')}else{px(c,ox+11,oy+8+bob,14,12,'#e8b79d');px(c,ox+9,oy+5+bob,18,7,pal.hair);px(c,ox+9,oy+8+bob,4,9,pal.hair);px(c,ox+24,oy+8+bob,3,9,pal.hair);px(c,ox+13,oy+14+bob,2,2,'#4d3c40');px(c,ox+21,oy+14+bob,2,2,'#4d3c40');px(c,ox+7,oy+20+bob,22,19,pal.robe);px(c,ox+9,oy+21+bob,18,16,pal.robe2);px(c,ox+16,oy+21+bob,4,17,pal.accent);px(c,ox+5,oy+23+bob,5,13,pal.robe2);px(c,ox+27,oy+23+bob,5,13,pal.robe2);px(c,ox+9+step,oy+37+bob,7,7,'#584b4d');px(c,ox+21-step,oy+37+bob,7,7,'#584b4d');if(job==='Noviço'){px(c,ox+12,oy+24+bob,12,3,pal.trim);px(c,ox+7,oy+28+bob,4,3,pal.accent)}else if(job==='Sacerdote'){px(c,ox+6,oy+19+bob,24,3,pal.trim);px(c,ox+11,oy+31+bob,15,3,pal.trim);px(c,ox+17,oy+3+bob,2,5,'#e8d8aa')}else{px(c,ox+6,oy+19+bob,24,3,pal.trim);px(c,ox+10,oy+29+bob,17,3,pal.trim);px(c,ox+7,oy+22+bob,3,15,pal.accent);px(c,ox+27,oy+22+bob,3,15,pal.accent);c.strokeStyle='#ffe8a5';c.lineWidth=1;c.beginPath();c.ellipse(ox+18,oy+3+bob,8,2,0,0,TAU);c.stroke()}}}
spriteCache.set(key,{sheet:s,fw,fh});return spriteCache.get(key)}
function makeMobSheet(type){const key=`m:${type}`;if(spriteCache.has(key))return spriteCache.get(key);const fw=type==='poring'?54:44,fh=type==='poring'?50:44,frames=4,rows=4,s=document.createElement('canvas');s.width=fw*frames;s.height=fh*rows;const c=s.getContext('2d');c.imageSmoothingEnabled=false;for(let r=0;r<rows;r++)for(let f=0;f<frames;f++){const ox=f*fw,oy=r*fh,bob=f===1?-1:f===3?1:0;if(type==='imp'){px(c,ox+12,oy+15+bob,20,20,'#b74d5a');px(c,ox+10,oy+11+bob,24,10,'#c55b66');px(c,ox+6,oy+6+bob,10,10,'#3d2632');px(c,ox+29,oy+6+bob,10,10,'#3d2632');px(c,ox+15,oy+19+bob,3,3,'#ffd38f');px(c,ox+27,oy+19+bob,3,3,'#ffd38f');px(c,ox+15,oy+35+bob,6,5,'#692939');px(c,ox+25,oy+35+bob,6,5,'#692939');px(c,ox+8,oy+24+bob,5,9,'#86404f');px(c,ox+32,oy+24+bob,5,9,'#86404f')}else if(type==='eye'){px(c,ox+7,oy+13+bob,30,19,'#76569d');px(c,ox+11,oy+16+bob,22,13,'#e7ddf5');px(c,ox+18,oy+17+bob,8,11,'#321944');px(c,ox+21,oy+20+bob,3,4,'#d98aff');px(c,ox+10,oy+31+bob,4,6,'#5c4777');px(c,ox+30,oy+31+bob,4,6,'#5c4777')}else if(type==='bat'){const flap=f%2?6:0;px(c,ox+18,oy+15+bob,9,14,'#4b4666');px(c,ox+2,oy+8+flap,17,8,'#55506f');px(c,ox+26,oy+8+flap,17,8,'#55506f');px(c,ox+7,oy+15+flap,9,5,'#3d3956');px(c,ox+29,oy+15+flap,9,5,'#3d3956');px(c,ox+19,oy+18+bob,2,2,'#ff668e');px(c,ox+25,oy+18+bob,2,2,'#ff668e')}else{const sq=f%2?2:0;px(c,ox+8,oy+11+sq,38,28-sq,'#7b1d50');px(c,ox+11,oy+8+sq,32,8,'#9a2d62');px(c,ox+5,oy+4+sq,11,12,'#27152d');px(c,ox+39,oy+4+sq,11,12,'#27152d');px(c,ox+18,oy+19+sq,4,4,'#211520');px(c,ox+33,oy+19+sq,4,4,'#211520');px(c,ox+25,oy+30+sq,7,2,'#ffc5dc');px(c,ox+15,oy+38,25,3,'rgba(40,15,28,.25)')}}spriteCache.set(key,{sheet:s,fw,fh});return spriteCache.get(key)}
function drawSprite(data,e,scale=2){const{sheet,fw,fh}=data,row=dirRow[e.dir]??0;let frame=e.moving?Math.floor(now/120)%4:0;if(e.attackingUntil>now||e.castingUntil>now)frame=2;const dw=fw*scale,dh=fh*scale;ctx.drawImage(sheet,frame*fw,row*fh,fw,fh,Math.round(e.x-dw/2),Math.round(e.y-dh+e.radius+8),dw,dh)}
function drawGround(){ctx.fillStyle='#78916d';ctx.fillRect(0,0,WORLD.width,WORLD.height);const tile=64;for(let y=0;y<WORLD.height;y+=tile)for(let x=0;x<WORLD.width;x+=tile){const n=((x/tile)*13+(y/tile)*7)%5;ctx.fillStyle=n<2?'#829978':'#748b69';ctx.fillRect(x,y,tile,tile);if(n===0){ctx.fillStyle='rgba(44,72,39,.22)';ctx.fillRect(x+14,y+18,2,9);ctx.fillRect(x+19,y+14,2,7)}}ctx.fillStyle='#aea28a';ctx.fillRect(1195,0,210,WORLD.height);for(let y=0;y<WORLD.height;y+=45){ctx.fillStyle=y%90?'#bdb39a':'#9a8d78';ctx.fillRect(1210,y+7,180,4)}ctx.fillStyle='#8f8574';ctx.fillRect(1140,600,320,250);ctx.fillStyle='#a99c86';for(let y=615;y<835;y+=30)for(let x=1155;x<1450;x+=42){ctx.fillRect(x,y,34,22)}for(let i=0;i<90;i++){const x=(i*211)%WORLD.width,y=(i*137)%WORLD.height;if(x>1150&&x<1450)continue;ctx.fillStyle=i%3?'rgba(235,229,171,.18)':'rgba(48,77,43,.22)';ctx.fillRect(x,y,3,8)}}
function drawChapel(s){const x=s.x-s.w/2,y=s.y-s.h/2;ctx.fillStyle='rgba(40,34,39,.25)';ctx.fillRect(x+16,y+75,s.w-32,s.h-55);ctx.fillStyle='#80777a';ctx.fillRect(x+18,y+65,s.w-36,s.h-65);ctx.fillStyle='#534b54';ctx.beginPath();ctx.moveTo(x,y+72);ctx.lineTo(s.x,y);ctx.lineTo(x+s.w,y+72);ctx.closePath();ctx.fill();ctx.fillStyle='#9b8d89';ctx.fillRect(s.x-42,y+92,84,113);ctx.fillStyle='#37303a';ctx.fillRect(s.x-22,y+125,44,80);ctx.fillStyle='#a9c3c1';for(const wx of[x+72,x+s.w-104]){ctx.fillRect(wx,y+105,32,48);ctx.fillStyle='#4e565d';ctx.fillRect(wx+14,y+105,4,48);ctx.fillRect(wx,y+126,32,4);ctx.fillStyle='#a9c3c1'}ctx.fillStyle='#5d5760';ctx.fillRect(s.x-8,y-35,16,45);ctx.fillRect(s.x-22,y-21,44,13)}
function drawScenery(s){if(s.type==='chapel')return drawChapel(s);if(s.type==='altar'){ctx.fillStyle='rgba(37,29,32,.22)';ctx.fillRect(s.x-86,s.y+18,172,26);ctx.fillStyle='#93898b';ctx.fillRect(s.x-78,s.y-20,156,48);ctx.fillStyle='#d4c9b2';ctx.fillRect(s.x-60,s.y-30,120,13);ctx.fillStyle='#ffe68e';ctx.fillRect(s.x-3,s.y-70,6,42);addStaticHalo(s.x,s.y-66);return}if(s.type==='grave'){ctx.fillStyle='rgba(30,25,28,.25)';ctx.fillRect(s.x-20,s.y+10,40,14);ctx.fillStyle='#817b78';ctx.fillRect(s.x-12,s.y-18,24,34);ctx.fillRect(s.x-19,s.y-10,38,8);return}if(s.type==='tree'){ctx.fillStyle='rgba(35,49,31,.28)';ctx.beginPath();ctx.ellipse(s.x,s.y+31,43,18,0,0,TAU);ctx.fill();ctx.fillStyle='#5c4938';ctx.fillRect(s.x-8,s.y-5,16,43);ctx.fillStyle='#435f3e';ctx.beginPath();ctx.arc(s.x-20,s.y-18,28,0,TAU);ctx.arc(s.x+16,s.y-21,31,0,TAU);ctx.arc(s.x,s.y-43,31,0,TAU);ctx.fill();ctx.fillStyle='#6d8654';ctx.beginPath();ctx.arc(s.x-13,s.y-39,14,0,TAU);ctx.fill();return}if(s.type==='crystal'){ctx.fillStyle='rgba(107,202,224,.22)';ctx.beginPath();ctx.arc(s.x,s.y,34,0,TAU);ctx.fill();ctx.fillStyle='#88d8e7';ctx.beginPath();ctx.moveTo(s.x,s.y-32);ctx.lineTo(s.x+17,s.y+7);ctx.lineTo(s.x,s.y+28);ctx.lineTo(s.x-14,s.y+5);ctx.closePath();ctx.fill();ctx.fillStyle='#cef8ff';ctx.fillRect(s.x-3,s.y-20,5,22);return}if(s.type==='pillar'){ctx.fillStyle='#7f7772';ctx.fillRect(s.x-15,s.y-45,30,58);ctx.fillStyle='#9c9189';ctx.fillRect(s.x-22,s.y-50,44,9);ctx.fillRect(s.x-22,s.y+10,44,9);return}if(s.type==='ruin'){ctx.fillStyle='#766f68';ctx.fillRect(s.x-34,s.y-15,68,27);ctx.fillStyle='#92887e';ctx.fillRect(s.x-21,s.y-29,43,17)}}
function addStaticHalo(x,y){ctx.save();ctx.globalAlpha=.18+.05*Math.sin(now/280);ctx.fillStyle='#fff0a0';ctx.beginPath();ctx.arc(x,y,30,0,TAU);ctx.fill();ctx.restore()}
function drawMob(m){if(m.id===selectedId){ctx.strokeStyle='#ffe99c';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(m.x,m.y+8,m.radius+10,m.radius*.55+6,0,0,TAU);ctx.stroke()}ctx.fillStyle='rgba(25,18,24,.25)';ctx.beginPath();ctx.ellipse(m.x,m.y+11,m.radius*1.1,Math.max(6,m.radius*.36),0,0,TAU);ctx.fill();ctx.save();if(m.flashUntil>now){ctx.globalAlpha=.55;ctx.filter='brightness(2)'}drawSprite(makeMobSheet(m.type),m,m.type==='poring'?1.65:1.72);ctx.restore();const w=m.boss?82:52,y=m.y-m.radius-50;ctx.fillStyle='rgba(20,14,20,.68)';ctx.fillRect(m.x-w/2,y,w,6);ctx.fillStyle=m.boss?'#e64b86':'#b94863';ctx.fillRect(m.x-w/2,y,w*clamp(m.hp/m.maxHp,0,1),6);ctx.fillStyle='#f0e8ee';ctx.font=m.boss?'700 11px sans-serif':'10px sans-serif';ctx.textAlign='center';ctx.fillText(m.name,m.x,y-6)}
function drawKyrieBarrier(){if(player.barrier<=0||player.barrierUntil<=now)return;const hp=clamp(player.barrier/(player.barrierMax||1),0,1),pulse=Math.sin(now/130)*2,spin=now/900;ctx.save();ctx.globalAlpha=.35+.35*hp;ctx.strokeStyle='#bdeaff';ctx.lineWidth=2;ctx.shadowBlur=16;ctx.shadowColor='#9bdcff';ctx.beginPath();ctx.ellipse(player.x,player.y-17,34+pulse,43+pulse,0,0,TAU);ctx.stroke();ctx.globalAlpha=.5;for(let i=0;i<8;i++){const a=i/8*TAU+spin;const x=player.x+Math.cos(a)*31,y=player.y-17+Math.sin(a)*39;ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.strokeRect(-3,-3,6,6);ctx.restore()}ctx.restore()}
function drawPlayer(p){ctx.fillStyle='rgba(25,18,24,.22)';ctx.beginPath();ctx.ellipse(p.x,p.y+11,18,8,0,0,TAU);ctx.fill();if(p===player)drawKyrieBarrier();ctx.save();if(p.flashUntil>now){ctx.globalAlpha=.6;ctx.filter='brightness(1.8)'}drawSprite(makePlayerSheet(p.job||'Noviço'),p,1.85);ctx.restore();ctx.fillStyle='#fff';ctx.font='700 11px sans-serif';ctx.textAlign='center';ctx.fillText(p.name||'Aventureiro',p.x,p.y+39);ctx.fillStyle='#d0c7d3';ctx.font='10px sans-serif';ctx.fillText(`${p.job||'Noviço'} • Nv. ${p.level||1}`,p.x,p.y+52)}
function glyphCross(x,y,size,color,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y-size);ctx.lineTo(x,y+size);ctx.moveTo(x-size*.65,y-size*.25);ctx.lineTo(x+size*.65,y-size*.25);ctx.stroke();ctx.restore()}
function drawFxItem(e){const t=clamp((now-e.born)/e.life,0,1),a=1-t;ctx.save();if(e.type==='slash'){ctx.globalAlpha=a;ctx.strokeStyle='#fff1c9';ctx.lineWidth=5*(1-t)+1;ctx.beginPath();ctx.arc(e.x,e.y-10,25,-.9,.8);ctx.stroke();}
else if(e.type==='healCaster'){ctx.globalAlpha=a;ctx.strokeStyle='#b9ffdf';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y+6,15+35*t,0,TAU);ctx.stroke();glyphCross(e.x,e.y-30-15*t,9,'#d5ffeb',a)}
else if(e.type==='healTarget'){ctx.globalAlpha=.8*a;ctx.fillStyle='rgba(180,255,220,.18)';ctx.fillRect(e.x-22,e.y-86+15*t,44,82);ctx.strokeStyle='#caffea';ctx.lineWidth=2;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(e.x,e.y+4,18+22*(t+i*.18),0,TAU);ctx.stroke()}glyphCross(e.x,e.y-48-12*t,12,'#e8fff3',a);for(let i=0;i<6;i++){const ang=i/6*TAU+now/500,rr=24+10*t;ctx.fillStyle='#d7ffed';ctx.fillRect(e.x+Math.cos(ang)*rr-2,e.y-20+Math.sin(ang)*rr-2,4,4)}}
else if(e.type==='magnificat'){const r=e.radius;ctx.globalAlpha=.9*a;ctx.strokeStyle='#ffe59c';ctx.lineWidth=2;ctx.shadowBlur=14;ctx.shadowColor='#ffe59c';for(let j=0;j<3;j++){ctx.beginPath();ctx.arc(e.x,e.y,lerp(36,r*(.5+j*.22),clamp(t*1.25-j*.12,0,1)),0,TAU);ctx.stroke()}ctx.globalAlpha=.65*a;for(let i=0;i<12;i++){const ang=i/12*TAU-now/950,rr=74+16*Math.sin(now/280+i);ctx.save();ctx.translate(e.x+Math.cos(ang)*rr,e.y+Math.sin(ang)*rr*.55);ctx.rotate(-ang);ctx.strokeRect(-4,-4,8,8);ctx.restore()}for(let i=0;i<7;i++){const yy=e.y+30-(t*145+i*18)%145;ctx.globalAlpha=.35*a;ctx.fillStyle='#fff3b8';ctx.fillRect(e.x-80+i*26,yy,3,18)}}
else if(e.type==='blessing'){ctx.globalAlpha=a;ctx.strokeStyle='#e4c8ff';ctx.lineWidth=2;ctx.shadowBlur=12;ctx.shadowColor='#d5b0ff';const y=e.y-78+50*t;ctx.beginPath();ctx.arc(e.x,y,22-6*t,0,TAU);ctx.stroke();for(let i=0;i<4;i++){const ang=i/4*TAU+Math.PI/4;ctx.beginPath();ctx.moveTo(e.x+Math.cos(ang)*10,y+Math.sin(ang)*10);ctx.lineTo(e.x+Math.cos(ang)*24,y+Math.sin(ang)*24);ctx.stroke()}glyphCross(e.x,y,11,'#fff1b8',a);ctx.globalAlpha=.35*a;ctx.fillStyle='#eedcff';ctx.fillRect(e.x-16,e.y-72,32,68)}
else if(e.type==='kyrieCast'){ctx.globalAlpha=a;ctx.strokeStyle='#bdeaff';ctx.lineWidth=2;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(e.x,e.y-16,25+22*t+i*6,34+28*t+i*7,0,0,TAU);ctx.stroke()}glyphCross(e.x,e.y-64-10*t,12,'#e8faff',a)}
else if(e.type==='kyrieBurst'){ctx.globalAlpha=a;ctx.strokeStyle='#bfeaff';ctx.lineWidth=3;ctx.shadowBlur=12;ctx.shadowColor='#9bdcff';ctx.beginPath();ctx.arc(e.x,e.y,lerp(18,e.radius,t),0,TAU);ctx.stroke();for(let i=0;i<8;i++){const ang=i/8*TAU,rr=lerp(20,e.radius*.82,t);ctx.save();ctx.translate(e.x+Math.cos(ang)*rr,e.y+Math.sin(ang)*rr);ctx.rotate(ang);ctx.strokeRect(-4,-4,8,8);ctx.restore()}}
else if(e.type==='guard'){ctx.globalAlpha=a;ctx.strokeStyle='#e7fbff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y-18,32,Math.PI*.2,Math.PI*.8);ctx.stroke();glyphCross(e.x,e.y-58,8,'#e7fbff',a)}
else if(e.type==='level'){ctx.globalAlpha=a;ctx.strokeStyle='#fff0a2';ctx.lineWidth=3;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(e.x,e.y,lerp(20,100+i*18,t),0,TAU);ctx.stroke()}glyphCross(e.x,e.y-70-30*t,14,'#fff7cc',a)}
else if(e.type==='purify'){ctx.globalAlpha=a;ctx.strokeStyle=e.boss?'#ffb7db':'#e7ddff';ctx.lineWidth=2;for(let i=0;i<5;i++){const rr=lerp(10,(e.boss?110:60)+i*4,t);ctx.beginPath();ctx.arc(e.x,e.y,rr,0,TAU);ctx.stroke()}glyphCross(e.x,e.y-40-20*t,e.boss?15:9,'#fff5dd',a)}ctx.restore()}
function drawEffects(){for(const e of fx)drawFxItem(e);for(const p of particles){const t=clamp((now-p.born)/p.life,0,1);ctx.save();ctx.globalAlpha=1-t;ctx.fillStyle=p.color;if(p.shape==='diamond'){ctx.translate(p.x,p.y);ctx.rotate(Math.PI/4);ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size)}else{ctx.beginPath();ctx.arc(p.x,p.y,p.size*(1-t*.5),0,TAU);ctx.fill()}ctx.restore()}for(const f of texts){const t=clamp((now-f.born)/f.life,0,1);ctx.save();ctx.globalAlpha=1-t;ctx.fillStyle=f.color;ctx.font='800 13px sans-serif';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y-t*34);ctx.restore()}}
function drawWorld(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(-camera.x,-camera.y);drawGround();const d=scenery.map(s=>({y:s.y+(s.type==='tree'?35:0),kind:'scene',v:s})).concat(mobs.filter(m=>m.alive).map(m=>({y:m.y,kind:'mob',v:m}))).concat([{y:player.y,kind:'player',v:player}]);d.sort((a,b)=>a.y-b.y);for(const o of d){if(o.kind==='scene')drawScenery(o.v);else if(o.kind==='mob')drawMob(o.v);else drawPlayer(o.v)}drawEffects();ctx.restore()}
function drawMinimap(){mctx.clearRect(0,0,minimap.width,minimap.height);mctx.fillStyle='#18231a';mctx.fillRect(0,0,minimap.width,minimap.height);const sx=minimap.width/WORLD.width,sy=minimap.height/WORLD.height;mctx.fillStyle='#9c927d';mctx.fillRect(1195*sx,0,210*sx,minimap.height);for(const m of mobs.filter(m=>m.alive)){mctx.fillStyle=m.boss?'#ff4d8e':'#bd5a72';mctx.beginPath();mctx.arc(m.x*sx,m.y*sy,m.boss?3:1.7,0,TAU);mctx.fill()}mctx.fillStyle='#fff2a3';mctx.beginPath();mctx.arc(player.x*sx,player.y*sy,3,0,TAU);mctx.fill()}
function updateUI(){ui.playerName.textContent=player.name;ui.classLabel.textContent=`${player.job} • Nv. ${player.level}`;ui.hpFill.style.width=`${clamp(player.hp/player.maxHp*100,0,100)}%`;ui.hpText.textContent=`${Math.ceil(player.hp)}/${player.maxHp}`;ui.spFill.style.width=`${clamp(player.sp/player.maxSp*100,0,100)}%`;ui.spText.textContent=`${Math.floor(player.sp)}/${player.maxSp}`;const need=xpNeeded(player.level);ui.xpFill.style.width=`${clamp(player.xp/need*100,0,100)}%`;ui.xpText.textContent=`${player.xp}/${need}`;const t=selectedMob();if(t){ui.targetPanel.classList.remove('hidden');ui.targetName.textContent=t.name;ui.targetHpFill.style.width=`${clamp(t.hp/t.maxHp*100,0,100)}%`;ui.targetHpText.textContent=`${Math.ceil(t.hp)} / ${t.maxHp} HP`}else ui.targetPanel.classList.add('hidden');ui.questProgress.textContent=objectiveComplete?'Concluída — o vale foi purificado':`Demônios purificados: ${Math.min(kills,12)} / 12`;for(const b of document.querySelectorAll('.skill')){const s=skills[b.dataset.skill],remaining=clamp(1-(now-s.last)/s.cooldown,0,1);b.classList.toggle('on-cooldown',remaining>0);const cd=b.querySelector('.cooldown');if(cd)cd.style.transform=`scaleY(${remaining})`}}
function frame(ts){now=ts;const dt=Math.min((ts-lastFrame)/1000,.05);lastFrame=ts;updatePlayer(dt);updateMobs(dt);updateEffects(dt);updateCamera();drawWorld();drawMinimap();updateUI();requestAnimationFrame(frame)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='1')cast('normal');if(k==='2')cast('heal');if(k==='3')cast('magnificat');if(k==='4')cast('blessing');if(k==='5')cast('kyrie');if(k===' ')cast('normal');if(k==='tab'){e.preventDefault();const alive=mobs.filter(m=>m.alive).sort((a,b)=>dist(player,a)-dist(player,b));if(!alive.length)return;const idx=Math.max(-1,alive.findIndex(m=>m.id===selectedId));selectMob(alive[(idx+1)%alive.length])}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
canvas.addEventListener('pointermove',e=>{mouse.worldX=e.clientX+camera.x;mouse.worldY=e.clientY+camera.y});canvas.addEventListener('pointerdown',e=>{mouse.worldX=e.clientX+camera.x;mouse.worldY=e.clientY+camera.y;const hit=mobs.filter(m=>m.alive&&Math.hypot(m.x-mouse.worldX,m.y-mouse.worldY)<m.radius+24).sort((a,b)=>dist(player,a)-dist(player,b))[0];if(hit){selectMob(hit);if(dist(player,hit)<=skills.normal.range+12)cast('normal');return}const p={radius:player.radius};if(blockedAt(p,mouse.worldX,mouse.worldY,{collideMobs:true})){toast('Esse local está bloqueado.');return}player.moveTarget={x:clamp(mouse.worldX,WORLD.margin,WORLD.width-WORLD.margin),y:clamp(mouse.worldY,WORLD.margin,WORLD.height-WORLD.margin)}});
document.querySelectorAll('.skill').forEach(b=>b.addEventListener('click',()=>cast(b.dataset.skill)));ui.helpToggle.addEventListener('click',()=>ui.helpContent.classList.toggle('hidden'));
log('Roweb visual v3 carregado: sprites clericais e efeitos sagrados aprimorados.','good');log('Colisão com cenário e monstros permanece ativa.','info');requestAnimationFrame(frame);
